### ISSUE TITLE
java.lang.IllegalStateException: Not allowed to start service Intent

### ISSUE THREAD

**Issue by kbarth** [beaconinside/beaconinside-android-sdk#3]
Is the SDK already targeting API >= 26? We receive an IllegalStateException caused by the sdk, which is trying to start the service while the app is in background: 

```javascript

02-22 14:13:37.537 7898-7898/*** E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: ***, PID: 7898
                                                                 java.lang.RuntimeException: Unable to create application ***.App: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.beaconinside.androidsdk.APPSTART cmp=***/com.beaconinside.androidsdk.BeaconService (has extras) }: app is in background uid UidRecord{12bf557 u0a117 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
                                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                  Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.beaconinside.androidsdk.APPSTART cmp=***/com.beaconinside.androidsdk.BeaconService (has extras) }: app is in background uid UidRecord{12bf557 u0a117 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
                                                                     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
                                                                     at android.app.ContextImpl.startService(ContextImpl.java:1477)
                                                                     at android.content.ContextWrapper.startService(ContextWrapper.java:650)
                                                                     at com.beaconinside.androidsdk.BeaconService.init(Unknown Source:49)
                                                                     at com.beaconinside.androidsdk.BeaconService.init(Unknown Source:1)
                                                                     at ***.App.onCreate(App.java:62)
                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
                                                                     at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                     at android.os.Looper.loop(Looper.java:164) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```
Is there an update planned to fix the service issues?

**Comment by bashtian** [comment]
Currently targetSdkVersion of 26 or higher are not yet supported by the SDK. 
There was a bugfix release of the SDK for fixing this issue https://github.com/beaconinside/beaconinside-android-sdk/releases/tag/v2.12.1
If you are using this version, can you please send me the device information of this crash report?

**Comment by kbarth** [comment]
Hi Bashtian, thank you for the quick replay. We are already using the latest release of the SDK and we still got the problem, that the app crashes if we quickly put the app in background before the beaconinside service is initialised. Which device informations do you need exactly? We have tested and reproduced this behavior on several devices (API 26 & 27), with the same result.

**Comment by bashtian** [comment]
This issue is fixed in our new Proximity SDK with full support for API 26 and above https://github.com/beaconinside/android-sdk
